### ISSUE TITLE
Entity_Id replaced after restart for all items

### ISSUE THREAD

**Issue by Lars-Hiller** [agustinmista/positron#20]
Thanks for the great tool! 
It really helped me a lot to get HomeAssistant to my AJAZZ stream deck.

Background:
After adding 18 items in one session - all working perfectly fine - restart of positron (after power outage) caused issues.

Issue:
All entity_ids have been replaced by the entity_id of the last item added. See screenshots.
All other settings still seem to be correct.
Image 1: List of items
Image 2: Correct entity_id for the (latest) item
Image 3: Wrong entity_id for all other items

Additional question: How to save (backup) all to avoid high effort "reparing"?

![Screenshot 2024-08-09 085223](https://github.com/user-attachments/assets/43dd9f15-dc61-419c-b925-9c36a0c8b6dc)
![Screenshot 2024-08-09 085300](https://github.com/user-attachments/assets/4d79d789-2f87-49dd-86a4-5d72b43afadd)
![Screenshot 2024-08-09 085339](https://github.com/user-attachments/assets/40d5a96f-55e6-4c26-93a5-f25fbe79e160)

**Comment by agustinmista** [comment]
Hey! Thanks for the feedback! 

The issue you're experiencing sounds quite weird. Which OS are you running the app on? If this happened after a power outage, my guess is that it could somehow be caused by the OS not having fully synced the config file to disk.

In any case, you should be able to open the config file directly from the settings menu:

`Settings -> Configuration file -> Open`

You can backup this file somewhere else in case you run into issues again (let me know if that's the case and I will investigate further) :)

**Comment by Lars-Hiller** [comment]
Hi,

thanks for the fast reply!

It is Positron 0.3.0 runnning on Win 11 (23H2). 

Before the outage it was running for some time. The power loss (actually me unplugging the laptop not noticing the battery had an issue and was empty) occured some hours after finalizing the itemas mentioned above. Hence it should not have been a syncing issue. 

Anyway, since then it is perfectly stable. And additionally I backedup the config file now. ;) 

Thanks a lot!
I will close this for now and keep you posted, if anything like this will happen again.
